name: "Publish Resume"
on:
  push:
    branches:
      - main

jobs:
  publish_resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Install the dependencies
        run: npm install resume-cli jsonresume-theme-github

      - name: Build the resume
        run: mkdir public && ./node_modules/.bin/resume export public/index.html --theme github

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
